apiVersion: v1
kind: Service
metadata:
  name: django-nginx-service2
spec:
  ports:
    - name: "django-nginx-service-port2"
      port: 8001
      targetPort: 8000
      nodePort: 32000
  selector:
    app: django-nginx2
  type: NodePort